AUDIT_ACTIONS = {
    // Authentication
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
    USER_REGISTRATION: 'USER_REGISTRATION',
    PASSWORD_CHANGE: 'PASSWORD_CHANGE',
    PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
    PASSWORD_RESET_COMPLETE: 'PASSWORD_RESET_COMPLETE',
    EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',

    // Super Admin Authentication
    SUPER_ADMIN_LOGIN: 'SUPER_ADMIN_LOGIN',
    SUPER_ADMIN_LOGOUT: 'SUPER_ADMIN_LOGOUT',
    SUPER_ADMIN_LOGIN_FAILED: 'SUPER_ADMIN_LOGIN_FAILED',

    // User Management
    USER_CREATED: 'USER_CREATED',
    USER_UPDATED: 'USER_UPDATED',
    USER_DELETED: 'USER_DELETED',
    USER_SESSION_REVOKED: 'USER_SESSION_REVOKED',
    USER_ACTIVATED: 'USER_ACTIVATED',
    USER_DEACTIVATED: 'USER_DEACTIVATED',
    USER_LOCKED: 'USER_LOCKED',
    USER_UNLOCKED: 'USER_UNLOCKED',

    // Role and Permission Management
    ROLE_ASSIGNED: 'ROLE_ASSIGNED',
    ROLE_REMOVED: 'ROLE_REMOVED',
    ROLE_UPDATED: 'ROLE_UPDATED',
    PERMISSION_GRANTED: 'PERMISSION_GRANTED',
    PERMISSION_REVOKED: 'PERMISSION_REVOKED',

    // Super Admin Actions
    SUPER_ADMIN_CREATED: 'SUPER_ADMIN_CREATED',
    SUPER_ADMIN_TOGGLED: 'SUPER_ADMIN_TOGGLED',
    SUPER_ADMIN_REVOKED: 'SUPER_ADMIN_REVOKED',
    CROSS_ORG_ACCESS: 'CROSS_ORG_ACCESS',
    SYSTEM_STATS_VIEWED: 'SYSTEM_STATS_VIEWED',

    // Organization Management
    ORGANIZATION_CREATED: 'ORGANIZATION_CREATED',
    ORGANIZATION_UPDATED: 'ORGANIZATION_UPDATED',
    ORGANIZATION_DELETED: 'ORGANIZATION_DELETED',
    ORGANIZATION_USER_TRANSFERRED: 'ORGANIZATION_USER_TRANSFERRED',

    // Security Events
    SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
    MULTIPLE_LOGIN_ATTEMPTS: 'MULTIPLE_LOGIN_ATTEMPTS',
    UNUSUAL_LOCATION_LOGIN: 'UNUSUAL_LOCATION_LOGIN',
    SESSION_HIJACK_ATTEMPT: 'SESSION_HIJACK_ATTEMPT',

    // API and Token Management
    API_KEY_CREATED: 'API_KEY_CREATED',
    API_KEY_REVOKED: 'API_KEY_REVOKED',
    TOKEN_REFRESH: 'TOKEN_REFRESH',

    // Two-Factor Authentication
    TWO_FA_ENABLED: 'TWO_FA_ENABLED',
    TWO_FA_DISABLED: 'TWO_FA_DISABLED',
    TWO_FA_VERIFIED: 'TWO_FA_VERIFIED',
    TWO_FA_FAILED: 'TWO_FA_FAILED',

    // System Events
    SYSTEM_MAINTENANCE: 'SYSTEM_MAINTENANCE',
    CONFIGURATION_CHANGED: 'CONFIGURATION_CHANGED',
    BULK_OPERATION: 'BULK_OPERATION'
}

RISK_LEVELS = {
    LOW: 'LOW',           // Normal operations
    MEDIUM: 'MEDIUM',     // Important changes
    HIGH: 'HIGH',         // Security-sensitive actions
    CRITICAL: 'CRITICAL'  // Super admin actions, security breaches
}

module.exports = { AUDIT_ACTIONS, RISK_LEVELS };